---

- name: Create GCP HA deployment
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
# Production
   client_id: Mu0V1ywgYteI6w1MbD15fKfVIUrNXGWC
   auth0_domain: netapp-cloud-account.auth0.com
   refToken: dBhriuz0KPvDW8hFMC_3aIToA38y8JVCNxTr8DAPMbr6U
  tasks:
    - name: Print Auth Domain
      debug: msg={{auth0_domain}}
    - name: Get Token
      uri:
        url: https://{{auth0_domain}}/oauth/token
        method: POST
        body_format: json
        return_content: yes
        body: {"grant_type":"refresh_token", "refresh_token": "{{refToken}}", "client_id": "{{client_id}}"}
        status_code: 200,204,202
      register: token_response
      ignore_errors: no
    - name: set token & token_type
      set_fact: token="{{ (token_response.content|from_json).access_token }}"
    - set_fact: token_type="{{ (token_response.content|from_json).token_type }}"
    - name: Create Template File For CVO
      template: src=../templates/gcp_ha_cvo.j2 dest={{ lookup('env', 'PWD') }}/templates/gcp_ha_cvo.json
    - name: Create OTC
      uri:
        url: "http://34.86.201.140/occm/api/gcp/ha/working-environments"
        method: POST
        headers:
           Authorization: "{{token_type}} {{ token }}"
           X-Tenancy-Account-Id: "account-46F1HgyQ"
           Referer: "Ansible"
        body_format: json
        body: "{{ lookup('file','../templates/gcp_ha_cvo.json') }}"
        status_code: 200,204,202
        timeout: 180
      register: otc_response